### ISSUE TITLE
For some reason lot of plugin stoped working

### ISSUE THREAD

**Issue by SilentX88** [StellarDev-org/SpaceDeltaSpigot#1]
**When the server starts this is the first notice:**
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Then some of plugins get this error:**
```
[01:22:16] [Server thread/ERROR]: Illegal method name "    ​‍​ ​ " in class org/json/simple/parser/ParseException initializing KoTH v1.5.1 (Is it up to date?)
java.lang.ClassFormatError: Illegal method name "    ​‍​ ​ " in class org/json/simple/parser/ParseException
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_282]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_282]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_282]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_282]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_282]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at subside.plugins.koth.modules.Lang.load(Lang.java:201) ~[?:?]
	at subside.plugins.koth.modules.Lang.onLoad(Lang.java:187) ~[?:?]
	at subside.plugins.koth.KothPlugin.trigger(KothPlugin.java:137) ~[?:?]
	at subside.plugins.koth.KothPlugin.onLoad(KothPlugin.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:207) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:568) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

```
[01:27:19 WARN]: [MassiveCore] Task #438 for MassiveCore v2.14.0 generated an exception
java.lang.ClassFormatError: Illegal method name "    ​‍​ ​ " in class org/json/simple/JSONObject
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_282]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_282]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_282]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_282]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_282]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_282]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_282]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:405) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at com.massivecraft.massivecore.Metrics.getServerData(Metrics.java:226) ~[?:?]
        at com.massivecraft.massivecore.Metrics.submitData(Metrics.java:247) ~[?:?]
        at com.massivecraft.massivecore.Metrics.access$100(Metrics.java:36) ~[?:?]
        at com.massivecraft.massivecore.Metrics$1$1.run(Metrics.java:159) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:790) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:720) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:623) [FactionDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

A few days ago that error started to appear and a lot of plugins just stopped working with SpaceDeltaSpigot
When I switch back to regular paper spigot all things is back to normal and everything working

**Comment by Gregor-Davies** [comment]
Do you have the plugins installed called "KothPlugin" or "Massivecore" it seems to be spewing some of the errors. Try uninstalling those plugins then try starting the server up again.

**Comment by BlazingTide** [comment]
I'm still getting this issue and it just randomly started happening.

**Comment by jacobp925** [comment]
This issue will be fixed soon, sorry.

Edit: Updated/fixed
