### ISSUE TITLE
ProtocolLib 4.7 error

### ISSUE THREAD

**Issue by benfiratkaya** [StellarDev-org/SpaceDeltaSpigot#2]
Hello I'm using Intave AntiCheat. And when I hit to any entity i get console error.
No problem for protocollib 4.6. Also this problem coming with SpaceDeltaSpigot + ProtocolLib 4.7

Error:
```
[21:30:38] [Netty Epoll Server IO #2/INFO]: [Intave] A RuntimeException occurred while processing a USE_ENTITY packet (j5.a)
[21:30:38] [Netty Epoll Server IO #2/WARN]: java.lang.RuntimeException: Unable to clone object PacketContainer[type=USE_ENTITY[class=PacketPlayInUseEntity, id=13], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private int net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a, private net.minecraft.server.v1_8_R3.PacketPlayInUseEntity$EnumEntityUseAction net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.action, private net.minecraft.server.v1_8_R3.Vec3D net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.c]]] (com.comphenix.protocol.events.PacketContainer)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at de.jpx3.intave.j5.a(j5.java:62)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at de.jpx3.intave.gen.irx.X17179079.invoke(<generated>)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at de.jpx3.intave.dn.onPacketReceiving(dn.java:26)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at de.jpx3.intave.dT.onPacketReceiving(dT.java:29)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:30:38] [Netty Epoll Server IO #2/WARN]: Caused by: java.io.IOException: Minecraft packet doesn't support DataOutputStream
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.events.PacketContainer.writeObject(PacketContainer.java:299)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1154)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:40)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	... 34 more
[21:30:38] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.IllegalArgumentException: None of [protected void java.lang.Object.finalize() throws java.lang.Throwable, public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public java.lang.String java.lang.Object.toString(), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException, public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll(), public java.lang.Object com.comphenix.protocol.utility.MinecraftMethods$1.delegate(java.util.concurrent.Callable,java.lang.reflect.Method) throws java.lang.Exception] allows for delegation from public abstract boolean io.netty.buffer.ByteBuf.readBoolean()
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1346)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:600)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5751)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.utility.MinecraftMethods.setupProxyConstructor(MinecraftMethods.java:199)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.utility.MinecraftMethods.initializePacket(MinecraftMethods.java:216)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.utility.MinecraftMethods.getPacketWriteByteBufMethod(MinecraftMethods.java:175)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.events.PacketContainer.writeObject(PacketContainer.java:294)
[21:30:38] [Netty Epoll Server IO #2/WARN]: 	... 44 more

```

**Comment by jacobp925** [comment]
Sounds like an issue with your anticheat, not the spigot.

**Comment by benfiratkaya** [comment]
> Sounds like an issue with your anticheat, not the spigot.

But this error coming with spacedeltaspigot. I tried with paper and no issue

**Comment by benfiratkaya** [comment]
any update?
